TrafficControl = TrafficControl or {}

TrafficControl.Config = {
    server = {
        requestPrefix = 'server:',
        commandName = 'trafficserver',
    },
    defaultMode = 'normal',
    profiles = {
        normal = {
            vehicleDensity = 1.0,
            randomVehicleDensity = 1.0,
            parkedVehicleDensity = 1.0,
            pedDensity = 1.0,
            scenarioPedDensity = 1.0,
            randomBoats = true,
            garbageTrucks = true,
            randomCops = true,
            randomCopsNotOnScenarios = true,
            randomCopsOnScenarios = true,
            parkedVehicleCount = 60,
            blockPopulationPeds = false,
        },
        none = {
            vehicleDensity = 0.0,
            randomVehicleDensity = 0.0,
            parkedVehicleDensity = 0.0,
            pedDensity = 0.0,
            scenarioPedDensity = 0.0,
            randomBoats = false,
            garbageTrucks = false,
            randomCops = false,
            randomCopsNotOnScenarios = false,
            randomCopsOnScenarios = false,
            parkedVehicleCount = 0,
            blockPopulationPeds = true,
        },
        low = {
            vehicleDensity = 0.6667,
            randomVehicleDensity = 0.6667,
            parkedVehicleDensity = 0.6667,
            pedDensity = 0.6667,
            scenarioPedDensity = 0.6667,
            randomBoats = false,
            garbageTrucks = false,
            randomCops = false,
            randomCopsNotOnScenarios = false,
            randomCopsOnScenarios = false,
            parkedVehicleCount = 40,
            blockPopulationPeds = false,
        },
        high = {
            vehicleDensity = 1.3333,
            randomVehicleDensity = 1.3333,
            parkedVehicleDensity = 1.3333,
            pedDensity = 1.3333,
            scenarioPedDensity = 1.3333,
            randomBoats = false,
            garbageTrucks = false,
            randomCops = false,
            randomCopsNotOnScenarios = false,
            randomCopsOnScenarios = false,
            parkedVehicleCount = 80,
            blockPopulationPeds = false,
        },
        full = {
            vehicleDensity = 2.0,
            randomVehicleDensity = 2.0,
            parkedVehicleDensity = 2.0,
            pedDensity = 2.0,
            scenarioPedDensity = 2.0,
            randomBoats = true,
            garbageTrucks = true,
            randomCops = true,
            randomCopsNotOnScenarios = true,
            randomCopsOnScenarios = true,
            parkedVehicleCount = 120,
            blockPopulationPeds = false,
        },
    },
    legacyModeDensity = {
        normal = 1.0,
        none = 0.0,
        low = 0.35,
        high = 0.7,
        full = 1.0,
    },
}
