-- Wires shared runtime state, internals, and NativeUI services across modules.
PerformanceTuning = PerformanceTuning or {}
PerformanceTuning._state = PerformanceTuning._state or {}
PerformanceTuning._internals = PerformanceTuning._internals or {}
PerformanceTuning.NativeUI = PerformanceTuning.NativeUI or {}

local state = PerformanceTuning._state
local internals = PerformanceTuning._internals
local nativeUI = PerformanceTuning.NativeUI
local runtimeState = PerformanceTuning.RuntimeState or {}
local runtimeConfig = PerformanceTuning.RuntimeConfig or {}
local bindings = PerformanceTuning.ClientBindings or {}
local definitions = PerformanceTuning.Definitions or {}
local menuSliders = PerformanceTuning.MenuSliders or {}
local tuningPackManager = PerformanceTuning.TuningPackManager or {}
local handlingFields = definitions.handlingFields or {}
local engineFields = definitions.engineFields or {}
local transmissionFields = definitions.transmissionFields or {}
local suspensionFields = definitions.suspensionFields or {}
local tireFields = definitions.tireFields or {}
local brakeFields = definitions.brakeFields or {}
local antirollFields = definitions.antirollFields or {}
local fieldTypeAliases = definitions.fieldTypeAliases or {}
local knownFieldTypes = definitions.knownFieldTypes or {}
local packDefinitions = definitions.packDefinitions or {}
local handlingManager = PerformanceTuning.HandlingManager or {}
local vehicleManager = PerformanceTuning.VehicleManager or {}

state.originalHandlingByVehicle = runtimeState.originalHandlingByVehicle
state.tuningStateByVehicle = runtimeState.tuningStateByVehicle
state.lastAppliedTuneStateByVehicle = runtimeState.lastAppliedTuneStateByVehicle
state.lastAppliedPiStateByVehicle = runtimeState.lastAppliedPiStateByVehicle
state.lastPiStateUpdatedAtByVehicle = runtimeState.lastPiStateUpdatedAtByVehicle
state.cachedEngineSwapValuesByModel = runtimeState.cachedEngineSwapValuesByModel
state.trackedVehiclesByKey = runtimeState.trackedVehiclesByKey
state.trackedVehicleKeys = runtimeState.trackedVehicleKeys

internals.HANDLING_CLASS = definitions.handlingClass
internals.StateBagKeys = definitions.stateBagKeys
internals.ENGINE_FIELDS = engineFields
internals.TRANSMISSION_FIELDS = transmissionFields
internals.SUSPENSION_FIELDS = suspensionFields
internals.TIRE_FIELDS = tireFields
internals.BRAKE_FIELDS = brakeFields
internals.ANTIROLL_FIELDS = antirollFields
internals.POWER_FIELD = handlingFields.engine and handlingFields.engine.power or nil
internals.TOP_SPEED_FIELD = handlingFields.engine and handlingFields.engine.topSpeed or nil
internals.DRAG_FIELD = handlingFields.engine and handlingFields.engine.drag or nil
internals.STEERING_LOCK_FIELD = handlingFields.steering and handlingFields.steering.lock or nil
internals.GEAR_FIELD = handlingFields.transmission and handlingFields.transmission.gear or nil
internals.CLUTCH_UPSHIFT_FIELD = handlingFields.transmission and handlingFields.transmission.clutchUpshift or nil
internals.BRAKE_FORCE_FIELD = handlingFields.brakes and handlingFields.brakes.force or nil
internals.TIRE_BIAS_FRONT_FIELD = handlingFields.tires and handlingFields.tires.biasFront or nil
internals.TIRE_MAX_FIELD = handlingFields.tires and handlingFields.tires.max or nil
internals.SUSPENSION_BIAS_FRONT_FIELD = handlingFields.suspension and handlingFields.suspension.biasFront or nil
internals.ANTIROLL_FORCE_FIELD = handlingFields.antiroll and handlingFields.antiroll.force or nil
internals.ANTIROLL_BIAS_FRONT_FIELD = handlingFields.antiroll and handlingFields.antiroll.biasFront or nil
internals.BRAKE_BIAS_FRONT_FIELD = handlingFields.brakes and handlingFields.brakes.biasFront or nil
internals.ENGINE_SWAP_MODEL_NAME = definitions.engineSwapModelName
internals.BRAKE_SCALING = runtimeConfig.brakeScaling
internals.FIELD_TYPE_ALIASES = fieldTypeAliases
internals.KNOWN_FIELD_TYPES = knownFieldTypes
internals.SUSPENSION_PACKS = packDefinitions.suspension
internals.TRANSMISSION_PACKS = packDefinitions.transmission
internals.ENGINE_PACKS = packDefinitions.engine
internals.TIRE_COMPOUND_PACKS = packDefinitions.tires
internals.BRAKE_PACKS = packDefinitions.brakes
internals.NITROUS_PACKS = packDefinitions.nitrous
internals.NITRO_PACKS = internals.NITROUS_PACKS
internals.NitrousConfig = runtimeConfig.nitrous
internals.Performance = definitions.performance
internals.trim = bindings.trim
internals.startsWith = bindings.startsWith
internals.isFiniteNumber = bindings.isFiniteNumber
internals.clampAntirollForceValue = menuSliders.clampAntirollForceValue
internals.clampBrakeBiasFrontValue = menuSliders.clampBrakeBiasFrontValue
internals.clampGripBiasFrontValue = menuSliders.clampGripBiasFrontValue
internals.clampAntirollBiasFrontValue = menuSliders.clampAntirollBiasFrontValue
internals.clampSuspensionRaiseValue = menuSliders.clampSuspensionRaiseValue
internals.clampSuspensionBiasFrontValue = menuSliders.clampSuspensionBiasFrontValue
internals.readHandlingValue = bindings.readHandlingValue
internals.writeHandlingValue = bindings.writeHandlingValue
internals.refreshVehicleAfterHandlingChange = bindings.refreshVehicleAfterHandlingChange
internals.applySuspensionRaiseLimitAdjustments = tuningPackManager.applySuspensionRaiseLimitAdjustments
internals.parseValueForType = handlingManager.parseValueForType
internals.formatHandlingValue = handlingManager.formatHandlingValue
internals.computeBrakeBarProgressForVehicle = bindings.computeBrakeBarProgressForVehicle
internals.getVehicleModelAudioName = bindings.getVehicleModelAudioName
internals.logInfo = bindings.logInfo
internals.normalizeSuspensionPackId = tuningPackManager.normalizeSuspensionPackId
internals.normalizeSteeringLockMode = tuningPackManager.normalizeSteeringLockMode
internals.clampNitroShotStrength = menuSliders.clampNitroShotStrength
internals.clearCustomPhysicsNitrousShot = bindings.clearCustomPhysicsNitrousShot
internals.requestDragRebalance = bindings.requestDragRebalance

nativeUI.state = nativeUI.state or {}
nativeUI.notify = bindings.notify
nativeUI.buildNormalizedSliderValues = menuSliders.buildNormalizedSliderValues
nativeUI.buildNitroShotSliderValues = menuSliders.buildNitroShotSliderValues
nativeUI.buildSuspensionClearanceSliderValues = menuSliders.buildSuspensionClearanceSliderValues
nativeUI.buildListState = bindings.buildListState
nativeUI.applyCurrentVehicleStateBagTuningForMenu = bindings.applyCurrentVehicleStateBagTuningForMenu
nativeUI.applyMenuSelection = bindings.applyMenuSelection
nativeUI.getCurrentVehicle = vehicleManager.getCurrentVehicle
nativeUI.ensureTuningState = bindings.ensureTuningState
nativeUI.syncVehicleTuneState = vehicleManager.syncVehicleTuneState
nativeUI.applyAntirollForceTweak = tuningPackManager.applyAntirollForceTweak
nativeUI.applyNitroShotStrengthTweak = tuningPackManager.applyNitroShotStrengthTweak
nativeUI.applyBrakeBiasFrontTweak = tuningPackManager.applyBrakeBiasFrontTweak
nativeUI.applyGripBiasFrontTweak = tuningPackManager.applyGripBiasFrontTweak
nativeUI.applyAntirollBiasFrontTweak = tuningPackManager.applyAntirollBiasFrontTweak
nativeUI.applySuspensionRaiseTweak = tuningPackManager.applySuspensionRaiseTweak
nativeUI.applySuspensionBiasFrontTweak = tuningPackManager.applySuspensionBiasFrontTweak
nativeUI.applySteeringLockModeTweak = tuningPackManager.applySteeringLockModeTweak
nativeUI.updateSavedVehicleTuningFile = vehicleManager.updateSavedVehicleTuningFile
nativeUI.resetPerformanceIndexDisplayState = bindings.resetPerformanceIndexDisplayState
nativeUI.drawPerformanceIndexPanel = bindings.drawPerformanceIndexPanel
nativeUI.getSliderValueForIndex = menuSliders.getSliderValueForIndex
nativeUI.getAntirollSliderIndex = menuSliders.getAntirollSliderIndex
nativeUI.getBrakeBiasSliderIndex = menuSliders.getBrakeBiasSliderIndex
nativeUI.getGripBiasSliderIndex = menuSliders.getGripBiasSliderIndex
nativeUI.getAntirollBiasSliderIndex = menuSliders.getAntirollBiasSliderIndex
nativeUI.getSuspensionRaiseSliderIndex = menuSliders.getSuspensionRaiseSliderIndex
nativeUI.getSuspensionBiasSliderIndex = menuSliders.getSuspensionBiasSliderIndex
nativeUI.getNitroShotSliderIndex = menuSliders.getNitroShotSliderIndex
nativeUI.getAntirollForceLabel = menuSliders.getAntirollForceLabel
nativeUI.getBrakeBiasFrontLabel = menuSliders.getBrakeBiasFrontLabel
nativeUI.getGripBiasFrontLabel = menuSliders.getGripBiasFrontLabel
nativeUI.getAntirollBiasFrontLabel = menuSliders.getAntirollBiasFrontLabel
nativeUI.getSuspensionRaiseLabel = menuSliders.getSuspensionRaiseLabel
nativeUI.getSuspensionBiasFrontLabel = menuSliders.getSuspensionBiasFrontLabel
nativeUI.getNitroShotStrengthLabel = menuSliders.getNitroShotStrengthLabel
nativeUI.getNitrousPackLabel = tuningPackManager.getNitrousPackLabel
nativeUI.clampAntirollForceValue = menuSliders.clampAntirollForceValue
nativeUI.clampBrakeBiasFrontValue = menuSliders.clampBrakeBiasFrontValue
nativeUI.clampGripBiasFrontValue = menuSliders.clampGripBiasFrontValue
nativeUI.clampAntirollBiasFrontValue = menuSliders.clampAntirollBiasFrontValue
nativeUI.clampSuspensionRaiseValue = menuSliders.clampSuspensionRaiseValue
nativeUI.clampSuspensionBiasFrontValue = menuSliders.clampSuspensionBiasFrontValue
nativeUI.clampNitroShotStrength = menuSliders.clampNitroShotStrength
nativeUI.sliderRanges = runtimeConfig.sliderRanges
nativeUI.tireBiasFrontField = handlingFields.tires and handlingFields.tires.biasFront or nil
